/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java.project;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

public class Main {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    System.out.println(new Main().getGreeting());

    try {
      ResourceBundle bundle = ResourceBundle.getBundle("application");
      String CONFIG_PATH = bundle.getString("CONFIG_PATH");
      String DB_URL = bundle.getString("DB_URL");
      String DB_USER = bundle.getString("DB_USER");
      String DB_PASSWORD = bundle.getString("DB_PASSWORD");

      System.out.println(CONFIG_PATH);
      System.out.println(DB_URL);
      System.out.println(DB_USER);
      System.out.println(DB_PASSWORD);

    } catch (MissingResourceException e) {
      e.printStackTrace();
    }
  }
}
