/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java.project;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class Main {

  static final Logger logger = LogManager.getLogger(Main.class.getName());

  public static void main(String[] args) {

    logger.info("START");

    logger.info("END");

  }
}
